features:
  ROLL_STICK:
    encoder: scalar
    minval: -1.0
    maxval: 1.0
    n: 100
    w: 21
  PITCH_STIC:
    encoder: scalar
    minval: -1.0
    maxval: 1.0
    n: 100
    w: 21

model_type: shared  # options: shared, separate

sp_params:
  column_count: 2048
  potential_pct: 0.8
  synapse_threshold: 0.5
  boost_strength: 0.0
  active_column_count: 40

tm_params:
  cells_per_column: 32
  initial_permanence: 0.21
  connected_permanence: 0.5
  permanence_increment: 0.1
  permanence_decrement: 0.1
  activation_threshold: 13
  min_threshold: 10
  max_new_synapse_count: 20
