encoder:
  rdse_features:
    - name: value
      min_val: 0
      max_val: 100
      resolution: 0.88
      n: 130
      w: 21
      seed: 42
  timeOfDay:
    n: 21
    rotation: 9.49

use_sp: True

sp:
  spatialImp: "cpp"
  potentialPct: 0.8
  columnCount: 2048
  inputWidth: 0
  boostStrength: 0.0
  numActiveColumnsPerInhArea: 40
  seed: 1956
  synPermActiveInc: 0.003
  synPermConnected: 0.2
  synPermInactiveDec: 0.0005

tm:
  column_dimensions: [2048]
  cells_per_column: 32
  activation_threshold: 22
  initial_permanence: 0.24
  connected_permanence: 0.12    # Lowered to allow more synapse connections
  min_threshold: 13
  max_new_synapse_count: 31
  permanence_increment: 0.06    # Slightly increased for stronger learning
  permanence_decrement: 0.008
  predicted_segment_decrement: 0.001
  seed: 1960
  max_segments_per_cell: 128
  max_synapses_per_segment: 128
  check_inputs: True
