encoder:
  rdse_features:
    - name: value
      min_val: 0
      max_val: 130
      n: 130
      w: 21

  timeOfDay:
    n: 21
    rotation: 9.49  # One full rotation per day

use_sp: true 

sp:
  inputDimensions: [151]
  columnDimensions: [2048]
  potentialPct: 0.8  #0.85
  synPermActiveInc: 0.003  #0.04
  synPermInactiveDec: 0.0005  #0.005
  boostStrength: 0.0
  seed: 1956  #42
#   "synPermConnected": 0.2,

tm:
  column_dimensions: [2048]
  cells_per_column: 32
  activation_threshold: 20  #13
  initial_permanence: 0.2  #0.21
  connected_permanence: 0.5  #0.2
  min_threshold: 13  #10
  max_new_synapse_count: 31  #20
  permanence_increment: 0.04  #0.1
  permanence_decrement: 0.008  #0.1
  predicted_segment_decrement: 0.01  #0.0
  max_segments_per_cell: 128  #255
  max_synapses_per_segment: 128
  seed: 1960  #42