features:
  value:
    encoder: scalar
    maxval: 100000
    minval: 0
    n: 700
    w: 21
model_type: shared
sp_params:
  input_dim: 100
  column_dim: 2048
  potential_pct: 0.8
  syn_perm_initial: 0.21
  syn_perm_active_inc: 0.04
  syn_perm_inactive_dec: 0.005
  connected_perm: 0.5
  boost_strength: 0.0
tm_params:
  column_dim: 2048
  cells_per_column: 32
  activation_threshold: 12
  initial_permanence: 0.21
  connected_permanence: 0.5
  # min_threshold: 9
  # max_new_synapses: 20         # ← FIXED!
  permanence_increment: 0.1
  permanence_decrement: 0.1
